//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.ProductStocks = new HashSet<ProductStock>();
        }
    
        public int BatchId { get; set; }
        public string BatchName { get; set; }
    
        public virtual ICollection<ProductStock> ProductStocks { get; set; }
    }
}
